### ISSUE TITLE
Move phpunit 5.6 from require to require-dev

### ISSUE THREAD

**Issue by enrobroy** [Algo-Web/ODataMetadata#131]
For purpose of non problematic install of POData that is using ODataMetadata as dedepency, for those who use phpunit in version 5.7 and above, please reconsider moving "phpunit/phpunit": "^5.6" from require to require-dev, as unnecessary dependency in non dev mode.

**Comment by CyberiaResurrection** [comment]
Thanks for trying POData out and taking the time to report this issue.  Good catch - phpunit is a -dev dependency in POData and POData-Laravel, so it should at least be consistently placed.

What made your install attempt(s) problematic?

To assuage my curiosity, how/where are you using POData?

**Comment by c-harris** [comment]
As the developer who fat fingered it to start with i would like to apologies for the issue and let you know we just merged up a pull request that should have fixed it. feel free to test and let us know.
