### ISSUE TITLE
Excel 2016 connect fails: InvalidVersionNumber: The EDMX version specified in the Version attribute does not match the version corresponding to the namespace of the Edmx element

### ISSUE THREAD

**Issue by jochendaum** [Algo-Web/ODataMetadata#139]
Hi,

I'm trying to use this project and algo-web/podata to deliver data from MySQL to Excel 2016. I have managed to set up a Sample data set on my local dev machine as follows:

http://dss.example.com/proto/odata.svc/ delivers a simple XML document:

`<service xml:base="http://dss.example.com/proto/odata.svc/"><workspace><atom:title>Default</atom:title><collection href="Samples"><atom:title>Samples</atom:title></collection></workspace></service>`

http://dss.example.com/proto/odata.svc/Samples in Chrome delivers my data as xml

http://dss.example.com/proto/odata.svc/Samples?$format=json in Chrome delivers my data as json, if I make a small tweak in JsonLightOdataWriter (I may create a separate issue)

I've collected the headers sent by Excel and replicated them in this curl call:

curl -H "User-Agent: Microsoft.Data.Mashup (https://go.microsoft.com/fwlink/?LinkID=304225)" -H "OData-MaxVersion: 4.0" -H "Accept: application/json;odata.metadata=minimal" -H "Accept-Encoding: gzip, deflate" -H "Host: dss.example.com" http://dss.example.com/proto/odata.svc/Samples

and that delivers my data as JSON as well. However, somehow it doesn't work in Excel.

When I put http://dss.example.com/proto/odata.svc/Samples into Excel as an OData source, I get an error message "No Writer can handle this request". This is the error I have when not making that tweak in JsonLightOdataWriter

Then I checked the odata.org examples and when I put them into Excel, I get the authentication popup. So I tried http://dss.example.com/proto/odata.svc/ in Excel and get the error message as per title. I assume it is related to output from http://dss.example.com/proto/odata.svc/$metadata, which is:

  | <?xml version="1.0" encoding="UTF-8"?>
-- | --
  | <edmx:Edmx xmlns:edmx="http://schemas.microsoft.com/ado/2007/06/edmx" xmlns="http://schemas.microsoft.com/ado/2009/11/edm" xmlns:cg="http://schemas.microsoft.com/ado/2006/04/codegeneration" xmlns:annotation="http://schemas.microsoft.com/ado/2009/02/edm/annotation" xmlns:m="http://schemas.microsoft.com/ado/2007/08/dataservices/metadata" Version="3.0">
  | <edmx:DataServices m:MaxDataServiceVersion="3.0" m:DataServiceVersion="3.0">
  | <Schema Namespace="Proto">
  | <EntityType OpenType="false" Abstract="false" Name="Sample">
  | <Key>
  | <PropertyRef Name="id"/>
  | </Key>
  | <Property Name="id" Type="Edm.Int64" Nullable="false"/>
  | <Property Name="firstName" Type="Edm.String" Nullable="false"/>
  | <Property Name="lastName" Type="Edm.String" Nullable="false"/>
  | <Property Name="companyName" Type="Edm.String" Nullable="false"/>
  | <Property Name="address" Type="Edm.String" Nullable="false"/>
  | <Property Name="city" Type="Edm.String" Nullable="false"/>
  | <Property Name="state" Type="Edm.String" Nullable="false"/>
  | <Property Name="post" Type="Edm.String" Nullable="false"/>
  | <Property Name="phone1" Type="Edm.String" Nullable="false"/>
  | <Property Name="phone2" Type="Edm.String" Nullable="false"/>
  | <Property Name="email" Type="Edm.String" Nullable="false"/>
  | <Property Name="web" Type="Edm.String" Nullable="false"/>
  | </EntityType>
  | <EntityContainer Name="Proto" m:IsDefaultEntityContainer="true">
  | <EntitySet Name="Proto" EntityType="Proto.Sample" cg:GetterAccess="Public"/>
  | </EntityContainer>
  | </Schema>
  | </edmx:DataServices>
  | </edmx:Edmx>
  |  

But I can't see anything that could be wrong.

Any idea what is missing here? Is there a guide to connect Excel to POData providers built with your project?

**Comment by kirill533** [comment]
Power BI was complaining about metadata: 

`InvalidVersionNumber : The EDMX version specified in the 'Version' attribute does not match the version corre
sponding to the namespace of the 'Edmx' element. : (0, 0) `

The problem was fixed after I modified the Version number in the edmx:Edmx tag from 3.0 to 1.0.

As it may be seen from examples, all samples below Odata 4.0 have edmx:Edmx tag with version 1.0:
* https://services.odata.org/V3/Northwind/Northwind.svc/$metadata
* https://services.odata.org/V3/OData/OData.svc/$metadata

Only sample of Odata v4 have it differently, but it also references different xmlns:edmx file:
* https://services.odata.org/V4/(S(ihhk0nudwyawubjpy1iucu5q))/TripPinServiceRW/$metadata

Same in ms docs: https://docs.microsoft.com/en-us/openspecs/windows_protocols/mc-edmx/44c78852-dd32-457b-a1ba-4f179bb00242


The fix needs to be applied in /src/MetadataV3/edmx/Edmx.php of ODataMetadata project:
Replacing 
`$this->setVersion($version);`
with 
`$this->setVersion('4.0' == $version ? '4.0' : '1.0');`

**Comment by c-harris** [comment]
With regards issues with json writers any help will be appricheated I have been meaning to make some major changes there

**Comment by kirill533** [comment]
> With regards issues with json writers any help will be appricheated I have been meaning to make some major changes there

Yes, Json Writers are still not perfect. I have hard time to make integration with Power BI fully working for me. And it is super hard to figure out, why that does not work. Would be good to have some means to automatically test that, maybe, some kind of integration tests involving OData libraries from Microsoft (C#). Do you know maybe some OData clients that might be used for proper testing of the API? 

P.S. Not sure about the right stop for such communication

**Comment by c-harris** [comment]
I think that is a good idea, we could probably build a c# integration test lib against the Northwood examples and test from there. Would be happy to work towards it.

What so you mean right stop for such communication?

**Comment by kirill533** [comment]
> What so you mean right stop for such communication?
Right "spot", sorry. "The right place".

**Comment by c-harris** [comment]
I probably agree I think the three simple options for us would be
1) you could create a new issue on podata?
2) you could shot me an email? 
3) we use discord.

Any of those suite you? A 4th might be I have an old skype account
